### ISSUE TITLE
Could not determine the dependencies of task ':cordapp-contracts-states:compileJava'.

### ISSUE THREAD

**Issue by hanubc7743** [amolpednekar/cordapp-token-ownable#1]
./gradlew runClient

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':cordapp-contracts-states:compileJava'.
> Could not create service of type AnnotationProcessorDetector using JavaGradleScopeServices.createAnnotationProcessorDetector().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

**Comment by amolpednekar** [comment]
Please run `./gradlew deployNodes` to first compile the CorDapp. 
Then `cd build/nodes` and `./runnodes`
After that you should run `./gradlew runClient`

These are standard deployment steps so I just linked the Corda tutorial, will update the readme with these additional instructions now nonetheless.

**Comment by hanubc7743** [comment]
> ./gradlew deployNodes

Still i am facing same error
./gradlew deployNodes

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileJava'.
> Could not create service of type AnnotationProcessorDetector using JavaGradleScopeServices.createAnnotationProcessorDetector().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

**Comment by amolpednekar** [comment]
I've tried it, works fine. 
Could be a problem with gradle. Add the stacktrace flag and check for more details.

**Comment by hanubc7743** [comment]
> I've tried it, works fine.
> Could be a problem with gradle. Add the stacktrace flag and check for more details.

Its working thank you for your quick response  Did you write above code in java?
